name: "HATEOAS at scale"

services:

  consul-service:
    image: hashicorp/consul:latest
    ports:
      - "8500:8500"
      - "8600:8600"
    command: [
      "agent",
      "-server",
      "-ui",
      "-node=server-1",
      "-bootstrap-expect=1",
      "-client=0.0.0.0",
      "-log-level=ERROR"
    ]
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8500/v1/agent/self" ]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      hateoas-at-scale-nw:
        ipv4_address: 172.25.0.5

  keycloak:
    container_name: "hateoasatscale-keycloak"
    image: "quay.io/keycloak/keycloak:latest"
    restart: "unless-stopped"
    ports:
      - "8010:8080"
    command: [ "start-dev", "--import-realm", "--log-level=INFO" ]
    environment:
      KC_HEALTH_ENABLED: true
      KC_BOOTSTRAP_ADMIN_USERNAME: "admin"
      KC_BOOTSTRAP_ADMIN_PASSWORD: "admin"
      KC_FEATURES: token-exchange,admin-fine-grained-authz
    volumes:
      - ./keycloak/data:/opt/keycloak/data/import
    networks:
      - hateoas-at-scale-nw

  users-service:
    image: openjdk:21-jdk-slim
    volumes:
      - "./users/build/libs/users-0.0.1-SNAPSHOT.jar:/app/app.jar"
    command: "java -jar /app/app.jar"
    depends_on:
      consul-service:
        condition: service_healthy
      keycloak:
        condition: service_started
    deploy:
      replicas: 1
    ports:
      - "8080:8080"
      - "4451:4451"
    networks:
      - hateoas-at-scale-nw

  products-service:
    image: openjdk:21-jdk-slim
    volumes:
      - "./products/build/libs/products-0.0.1-SNAPSHOT.jar:/app/app.jar"
    command: "java -jar /app/app.jar"
    depends_on:
      consul-service:
        condition: service_healthy
      keycloak:
        condition: service_started
    deploy:
      replicas: 1
    ports:
      - "8081:8080"
      - "4452:4451"
    networks:
      - hateoas-at-scale-nw

  carts-service:
    image: openjdk:21-jdk-slim
    volumes:
      - "./cart/build/libs/cart-0.0.1-SNAPSHOT.jar:/app/app.jar"
    command: "java -jar /app/app.jar"
    depends_on:
      consul-service:
        condition: service_healthy
      keycloak:
        condition: service_started
    deploy:
      replicas: 1
    ports:
      - "8082:8080"
      - "4453:4451"
    networks:
      - hateoas-at-scale-nw

  nginx-gateway:
    image: nginx:latest
    container_name: "nginx-gateway"
    ports:
      - "8020:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      hateoas-at-scale-nw:
        ipv4_address: 172.25.0.10

  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    depends_on:
      nginx-gateway:
        condition: service_started
      users-service:
        condition: service_started
      carts-service:
        condition: service_started
      products-service:
        condition: service_started
      keycloak:
        condition: service_started
    ports:
      - "4200:4200"
    networks:
      hateoas-at-scale-nw:
        ipv4_address: 172.25.0.9

networks:
  hateoas-at-scale-nw:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16
          gateway: 172.25.0.1

