name: "HATEOAS at scale"

services:
  keycloak:
    container_name: "hateoasatscale-keycloak"
    image: "quay.io/keycloak/keycloak:latest"
    restart: "unless-stopped"
    ports:
      - "8010:8080"
    command: ["start-dev", "--import-realm", "--log-level=INFO"]
    environment:
      KC_HEALTH_ENABLED: true
      KC_BOOTSTRAP_ADMIN_USERNAME: "admin"
      KC_BOOTSTRAP_ADMIN_PASSWORD: "admin"
      KC_FEATURES: token-exchange,admin-fine-grained-authz
    volumes:
        - ./keycloak/data:/opt/keycloak/data/import
    networks:
      - hateoas-at-scale-nw

  kong-gateway:
    image: "kong/kong-gateway:3.10.0.0"
    environment:
      KONG_DATABASE: off
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_GUI_URL: http://localhost:8002
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_PROXY_LISTEN: 0.0.0.0:8000
      KONG_DNS_RESOLVER: 172.25.0.5:8600
      KONG_DECLARATIVE_CONFIG: /opt/kong/kong.yml
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
      - "8003:8003"
      - "8004:8004"
    depends_on:
      consul-service:
        condition: service_healthy
    volumes:
      - ./kong:/opt/kong
    healthcheck:
      test: [ "CMD", "kong", "health" ]
      interval: 10s
      timeout: 10s
      retries: 10
    restart: on-failure:5
    networks:
      hateoas-at-scale-nw:
        ipv4_address: 172.25.0.10

  consul-service:
    image: hashicorp/consul:latest
    ports:
      - "8500:8500"
      - "8600:8600"
    command: [
      "agent",
      "-server",
      "-ui",
      "-node=server-1",
      "-bootstrap-expect=1",
      "-client=0.0.0.0",
      "-log-level=ERROR"
    ]
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8500/v1/agent/self" ]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      hateoas-at-scale-nw:
        ipv4_address: 172.25.0.5

  users-service:
    image: openjdk:21-jdk-slim
    volumes:
      - "./users/build/libs/users-0.0.1-SNAPSHOT.jar:/app/app.jar"
    command: "java -jar /app/app.jar"
    depends_on:
      consul-service:
        condition: service_healthy
    deploy:
      replicas: 1
    ports:
      - "8080:8080"
      - "4451:4451"
    networks:
      - hateoas-at-scale-nw

  products-service:
    image: openjdk:21-jdk-slim
    volumes:
      - "./products/build/libs/products-0.0.1-SNAPSHOT.jar:/app/app.jar"
    command: "java -jar /app/app.jar"
    depends_on:
      consul-service:
        condition: service_healthy
    deploy:
      replicas: 3
    ports:
      - "8081:8080"
      - "4452:4451"
    networks:
      - hateoas-at-scale-nw

  cart-service:
    image: openjdk:21-jdk-slim
    volumes:
      - "./cart/build/libs/cart-0.0.1-SNAPSHOT.jar:/app/app.jar"
    command: "java -jar /app/app.jar"
    depends_on:
      consul-service:
        condition: service_healthy
    deploy:
      replicas: 3
    ports:
      - "8082:8080"
      - "4453:4451"
    networks:
      - hateoas-at-scale-nw

  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    depends_on:
      kong-gateway:
        condition: service_healthy
      users-service:
        condition: service_started
      cart-service:
        condition: service_started
      products-service:
        condition: service_started
    ports:
      - "4200:4200"
    networks:
      hateoas-at-scale-nw:
        ipv4_address: 172.25.0.9

networks:
  hateoas-at-scale-nw:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16
          gateway: 172.25.0.1

