name: "HATEOAS @ scale"

services:
  users:
    container_name: users
    build:
      context: ./users
      dockerfile: ../Dockerfile
    volumes:
      - ./users/build/libs:/
    ports:
      - "8080:8080"
    networks:
      - hateoas-at-scale-nw

  cart:
    container_name: cart
    build:
      context: ./cart
      dockerfile: ../Dockerfile
    volumes:
      - ./cart/build/libs:/
    ports:
      - "8081:8080"
    networks:
      - hateoas-at-scale-nw

  products:
    container_name: products
    build:
      context: ./products
      dockerfile: ../Dockerfile
    volumes:
      - ./products/build/libs:/
    ports:
      - "8082:8080"
    networks:
      - hateoas-at-scale-nw

networks:
  hateoas-at-scale-nw:
    name: hateoas-at-scale-nw
    driver: bridge
