server:
  port: 8080
  error:
    whitelabel:
      enabled: false
  forward-headers-strategy: native
  undertow:
    preserve-path-on-forward: true

spring:
  application:
    name: users-service
  profiles:
    active: dev
  banner:
    location: classpath:/banner.txt
  cloud:
    consul:
      host: consul-service
      port: 8500
      discovery:
        prefer-ip-address: true
        instance-id: ${spring.application.name}:${spring.application.instance-id:${random.value}}
        service-name: ${spring.application.name}
      enabled: true
    loadbalancer:
      x-forwarded:
        enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://keycloak:8080/realms/hateoasatscale"
          jwk-set-uri: "http://keycloak:8080/realms/hateoasatscale/protocol/openid-connect/certs"
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

management:
  httpexchanges:
    recording:
      enabled: true
      include: request-headers, response-headers
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: [info,health,metrics,mappings]
  server:
    port: 4451

logging:
  level:
    org:
      apache:
        http:
          wire=DEBUG:
