spring:
  application:
    name: users-service
  profiles:
    active: dev
  banner:
    location: classpath:/banner.txt
  cloud:
    consul:
      host: consul-service
      port: 8500
      discovery:
        prefer-ip-address: true
        instance-id: ${spring.application.name}:${spring.application.instance-id:${random.value}}
        service-name: ${spring.application.name}
      enabled: true

server:
  port: 8080
  error:
    whitelabel:
      enabled: false

management:
  server:
    port: 4451

app:
  frontend:
    base-url: http://localhost:4200