_format_version: "3.0"
_transform: true

services:
  - name: users-service
    protocol: http
    host: users.service.consul
    port: 8081
    routes:
      - name: users-route
        paths:
          - /users
        strip_path: false
        plugins:
          - name: request-transformer
            config:
              add:
                headers:
                  - "X-Forwarded-Host: $host"
                  - "X-Forwarded-Port: $port"
                  - "X-Forwarded-Proto: $scheme"
                  - "X-Forwarded-Prefix: /users"
upstreams:
  - name: users-upstream
    targets:
      - target: users-service.service.consul:8080