_format_version: "3.0"
_transform: true

services:
  - name: users-service
    protocol: http
    host: users-service.service.consul
    port: 8081
    routes:
      - name: users-route
        paths:
          - /users
        strip_path: true
        preserve_host: true
        methods: ["GET", "POST", "PUT", "DELETE", "PATCH"]
        headers:
          X-Forwarded-Host: ["localhost"]
          X-Forwarded-Port: ["8000"]
          X-Forwarded-Proto: ["http", "https"]

  - name: products-service
    protocol: http
    host: products-service.service.consul
    port: 8082
    routes:
      - name: products-route
        paths:
          - /products
        strip_path: true
        preserve_host: true
        methods: ["GET", "POST", "PUT", "DELETE", "PATCH"]
        headers:
          X-Forwarded-Host: ["localhost"]
          X-Forwarded-Port: ["8000"]
          X-Forwarded-Proto: ["http", "https"]

  - name: cart-service
    protocol: http
    host: cart-service.service.consul
    port: 8080
    routes:
      - name: cart-route
        paths:
          - /cart
        strip_path: true
        preserve_host: true
        methods: ["GET", "POST", "PUT", "DELETE", "PATCH"]
        headers:
          X-Forwarded-Host: ["localhost"]
          X-Forwarded-Port: ["8000"]
          X-Forwarded-Proto: ["http", "https"]
