spring:
  application:
    name: products-service
  profiles:
    active: dev
  banner:
    location: classpath:/banner.txt
  cloud:
    consul:
      host: consul-service
      port: 8500
      discovery:
        prefer-ip-address: true
        instance-id: ${spring.application.name}:${spring.application.instance-id:${random.value}}
        service-name: ${spring.application.name}
      enabled: true

server:
  port: 8080
  error:
    whitelabel:
      enabled: false

management:
  server:
    port: 4452

application:
  network:
    gateway-url: http://172.25.0.10:8000
    services:
      carts:
        name: carts-service
        endpoints:
          add: carts
