spring:
  application:
    name: cart
  profiles:
    active: dev
  banner:
    location: classpath:/banner.txt
  cloud:
    consul:
      host: consul-service
      discovery:
        instance-id: ${spring.application.name}:${spring.application.instance-id:${random.value}}
        health-check-path: ${management.server.servlet.context-path}/health
        health-check-interval: 15s
server:
  error:
    whitelabel:
      enabled: 'false'
  forward-headers-strategy: framework

management:
  server:
    port: 4452