server:
  port: 8080
  error:
    whitelabel:
      enabled: false
  forward-headers-strategy: native

spring:
  application:
    name: carts-service
  profiles:
    active: dev
  banner:
    location: classpath:/banner.txt
  cloud:
    consul:
      host: consul-service
      port: 8500
      discovery:
        prefer-ip-address: true
        instance-id: ${spring.application.name}:${spring.application.instance-id:${random.value}}
        service-name: ${spring.application.name}
      enabled: true
    loadbalancer:
      x-forwarded:
        enabled: true
    openfeign:
      client:
        config:
          products-service:
            default-request-headers:
              X-Forwarded-For: localhost
              X-Forwarded-Host: localhost
              X-Forwarded-Prefix: /products-service
              X-Forwarded-Port: 8020
              X-Forwarded-Proto: http
          users-service:
            default-request-headers:
              X-Forwarded-For: localhost
              X-Forwarded-Host: localhost
              X-Forwarded-Prefix: /users-service
              X-Forwarded-Port: 8020
              X-Forwarded-Proto: http
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://keycloak:8080/realms/hateoasatscale"
          jwk-set-uri: "http://keycloak:8080/realms/hateoasatscale/protocol/openid-connect/certs"
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: [info,health,metrics,mappings]
  server:
    port: 4450

logging:
  level:
    org:
      apache:
        http:
          wire=DEBUG:
