spring:
  application:
    name: carts-service
  profiles:
    active: dev
  banner:
    location: classpath:/banner.txt
  cloud:
    consul:
      host: consul-service
      port: 8500
      discovery:
        prefer-ip-address: true
        instance-id: ${spring.application.name}:${spring.application.instance-id:${random.value}}

server:
  port: 8080
  error:
    whitelabel:
      enabled: false

management:
  server:
    port: 4450