spring:
  application:
    name: carts-service
  profiles:
    active: dev
  banner:
    location: classpath:/banner.txt
  cloud:
    consul:
      host: consul-service
      port: 8500
      discovery:
        prefer-ip-address: true
        instance-id: ${spring.application.name}:${spring.application.instance-id:${random.value}}
        service-name: ${spring.application.name}
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://keycloak:8080/realms/hateoasatscale"
          jwk-set-uri: "http://keycloak:8080/realms/hateoasatscale/protocol/openid-connect/certs"
        client-id: hateoasatscale
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

server:
  port: 8080
  error:
    whitelabel:
      enabled: false

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: [info,health,metrics,mappings]

    env:
      enabled: true
  server:
    port: 4450
